### PR TITLE
Added checklist for admins

### PR DESCRIPTION
**Pull request by Yonet**
@AdaRoseCannon and @cwilso, I've added a checklist for WG repos to be added to the IPR tool. Requirements for CG to be moved will be the same with different links for:

* license
* CoC
* Contributing

If you think this looks good, I can make the CG version. 

Thanks!

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
This looks really good! Thanks for adding the links!

**Comment by cwilso** [comment]
Do we need this?  The repo manager will automatically do this for you.

**Comment by AdaRoseCannon** [comment]
Oh! Then perhaps the bits entirely handled by the repo manager can be a single check box, but other actions that need to be taken are good to have in the list.

**Comment by himorin** [comment]
In addition to this sort of checklist, I've thought of template of README.md to be used for migration.
For checklist itself, I propose to have some for CG to WG. While I've edited files for recent migration from CG to WG, I checked `w3c.json` for `type`, `index.bs` for `Status`, etc. Even the [repo manager](https://labs.w3.org/repo-manager/) has checkbox to add `w3c.json`, `CONTRIBUTING.md`, `LICENSE.md`, `README.md`, and `CODE_OF_CONDUCT.md`, it will not check and update these status lines which already exist (I think,,, could be wrong although...).

**Pull request closed without merging**
